force-app/main/default/objects/Default_Search_Settings__mdt/Default_Search_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Default Search Setting</label>
    <pluralLabel>Default Search Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Default_Search_Settings__mdt/fields/Community_Condition_Expression__c.field-meta.xml
<CustomField>
    <fullName>Community_Condition_Expression__c</fullName>
    <label>Community Condition Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Default_Search_Settings__mdt/fields/Condition_Expression__c.field-meta.xml
<CustomField>
    <fullName>Condition_Expression__c</fullName>
    <label>Condition Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Default_Search_Settings__mdt/fields/Knowledge_Fields_To_Retrieve__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Fields_To_Retrieve__c</fullName>
    <label>Knowledge Fields To Retrieve</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Default_Search_Settings__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Default_Search_Settings__mdt/fields/Search_Query__c.field-meta.xml
<CustomField>
    <fullName>Search_Query__c</fullName>
    <label>Search Query</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MetadataService.cls
public with sharing class MetadataService {
  public List<Default_Search_Settings__mdt> getDefaultSearchSettings(
    String objectName
  ) {
    return [
      SELECT
        Search_Query__c,
        Knowledge_Fields_To_Retrieve__c,
        Condition_Expression__c,
        Community_Condition_Expression__c
      FROM Default_Search_Settings__mdt
      WHERE Object__c = :objectName
    ];
  }

  public List<InsightBase_User_Actions__mdt> getUserActions() {
    return [
      SELECT
        DeveloperName,
        MasterLabel,
        Action_Order__c,
        Action_Type__c,
        Method_Name__c,
        Service_Class__c
      FROM InsightBase_User_Actions__mdt
      LIMIT 100
    ];
  }
}