force-app/main/default/objects/Knowledge_Community__c/Knowledge_Community__c.object-meta.xml
<CustomObject>
    <label>Knowledge Community</label>
    <nameField>
        <label>Knowledge Community Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Communities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Community__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KnowledgeServices.cls
public with sharing class KnowledgeServices {
  public Map<String, Object> getUserCommunities() {
    try {
      Map<String, Object> communities = new Map<String, Object>();
      KnowledgeUtils KUtils = new KnowledgeUtils();
      List<Knowledge_Community__c> response = KUtils.getAllCommunities();
      for (Knowledge_Community__c comm : response) {
        Map<String, String> commDetails = new Map<String, String>();
        commDetails.put('Id', comm.Id);
        commDetails.put('name', comm.name);
        commDetails.put('logo', comm.Logo__c);
        communities.put(comm.Id, commDetails);
      }
      return communities;
    } catch (AuraHandledException e) {
      throw e;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}