force-app/main/default/objects/Knowledge_Comment__c/Knowledge_Comment__c.object-meta.xml
<CustomObject>
    <label>Knowledge Comment</label>
    <nameField>
        <displayFormat>CMNT-{0000000000}</displayFormat>
        <label>Comment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge  Comments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Comment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge_Comment__c/fields/date_created__c.field-meta.xml
<CustomField>
    <fullName>date_created__c</fullName>
    <label>date created</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge_Comment__c/fields/Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>Knowledge  Comments</relationshipLabel>
    <relationshipName>Knowledge_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Knowledge_Comment__c/fields/Knowledge_Comment__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Comment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge Comment</label>
    <referenceTo>Knowledge_Comment__c</referenceTo>
    <relationshipLabel>Knowledge  Comments</relationshipLabel>
    <relationshipName>Knowledge_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CommentServices.cls
public with sharing class CommentServices {
  @AuraEnabled
  public static void addComment(Map<String, String> params) {
    try {
      List<Knowledge_Comment__c> commentList = new List<Knowledge_Comment__c>();
      Knowledge_Comment__c commentToAdd = new Knowledge_Comment__c();
      commentToAdd.Comment__c = params.get('body');
      commentToAdd.Knowledge__c = params.get('contentId');
      commentToAdd.date_created__c = Datetime.now();
      if (!String.isBlank(params.get('replyTo'))) {
        commentToAdd.Knowledge_Comment__c = params.get('replyTo');
      }
      commentList.add(commentToAdd);
      insert commentList;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  @AuraEnabled(cacheable=true)
  public static List<Knowledge_Comment__c> getAllComments(String contentId) {
    try {
      List<Knowledge_Comment__c> comments = [
        SELECT
          Id,
          Name,
          Comment__c,
          CreatedById,
          Knowledge__c,
          Knowledge_Comment__c,
          date_created__c
        FROM Knowledge_Comment__c
        WHERE Knowledge__c = :contentId
        LIMIT 50
      ];
      return comments;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}